In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [ ]:
df = pd.get_dummies(df, columns=['Gender','Geography'],drop_first=True)

In [ ]:
x = df.drop(['Exited'],axis=1)
y = df['Exited']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
def build_model(a_func):
    model = Sequential()
    model.add(Dense(16,input_dim=x_train.shape[1],activation=a_func))
    model.add(Dense(8,activation=a_func))
    model.add(Dense(1,activation='sigmoid'))
    model.compile(optimizer='adam', loss='binary_crossentropy')
    return model

In [ ]:
activations = ['relu','sigmoid','tanh']
results = {}

In [ ]:
for a in activations:
    print(f"\nTraining model with {a}")
    model = build_model(a)
    model.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_test,y_test))

    y_pred = (model.predict(x_test)>0.5).astype(int)

    print("\nModel Performance:")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Training model with relu
Epoch 1/10


C:\Users\kprat\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.8053 - val_loss: 0.5559
Epoch 2/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5242 - val_loss: 0.4387
Epoch 3/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4466 - val_loss: 0.4092
Epoch 4/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4188 - val_loss: 0.3868
Epoch 5/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - loss: 0.3895 - val_loss: 0.3645
Epoch 6/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - loss: 0.3701 - val_loss: 0.3538
Epoch 7/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3603 - val_loss: 0.3449
Epoch 8/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3418 - val_loss: 0.3414
Epoch 9/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3569 - val_loss: 0.3402
Epoch 10/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3367 - val_loss: 0.3392
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step

Model Performance:
Accuracy: 0.8643333333333333
Confusion Matrix:
 [[2324   92]
 [ 315  269]]

Training 

C:\Users\kprat\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.5297 - val_loss: 0.4780
Epoch 2/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4903 - val_loss: 0.4563
Epoch 3/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4744 - val_loss: 0.4351
Epoch 4/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4410 - val_loss: 0.4220
Epoch 5/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4400 - val_loss: 0.4163
Epoch 6/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4309 - val_loss: 0.4140
Epoch 7/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4282 - val_loss: 0.4112
Epoch 8/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4237 - val_loss: 0.4100
Epoch 9/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4235 - val_loss: 0.4070
Epoch 10/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4326 - val_loss: 0.4050
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step

Model Performance:
Accuracy: 0.824
Confusion Matrix:
 [[2337   79]
 [ 449  135]]

Training model with tanh
E

C:\Users\kprat\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6144 - val_loss: 0.4379
Epoch 2/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4356 - val_loss: 0.4129
Epoch 3/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4298 - val_loss: 0.4075
Epoch 4/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4293 - val_loss: 0.4001
Epoch 5/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4233 - val_loss: 0.3896
Epoch 6/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4225 - val_loss: 0.3782
Epoch 7/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3879 - val_loss: 0.3682
Epoch 8/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3787 - val_loss: 0.3582
Epoch 9/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3727 - val_loss: 0.3509
Epoch 10/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3737 - val_loss: 0.3452
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step

Model Performance:
Accuracy: 0.8626666666666667
Confusion Matrix:
 [[2342   74]
 [ 338  246]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [ ]:
df = pd.get_dummies(df, columns=['Geography','Gender'],drop_first=True)

In [ ]:
# scaler = StandardScaler()
# x_train = scaler.fit_transform(x_train)
# x_test = scaler.transform(x_test)

In [ ]:
x = df.drop(['Exited'],axis=1)
y = df['Exited']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
def build_model(a_func):
    model = Sequential()
    model.add(Dense(16,input_dim=x_train.shape[1],activation=a))
    model.add(Dense(8,activation=a))
    model.add(Dense(1,activation='sigmoid'))
    model.compile(optimizer='adam',loss='binary_crossentropy')
    return model

In [ ]:
activations = ['relu','sigmoid','tanh']
for a in activations:
    print(f"\n training model with {a} activation function")
    model = build_model(a)
    model.fit(x_train,y_train,epochs=10, batch_size=32, validation_data=(x_test,y_test))

    y_pred = (model.predict(x_test)>0.5).astype(int)

    print("\nPerformance:\n")
    print("Accuracy:",accuracy_score(y_test,y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred))


 training model with relu activation function
Epoch 1/10


C:\Users\kprat\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5299 - val_loss: 0.4533
Epoch 2/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4574 - val_loss: 0.4249
Epoch 3/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4286 - val_loss: 0.4135
Epoch 4/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4259 - val_loss: 0.4055
Epoch 5/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4198 - val_loss: 0.3984
Epoch 6/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4199 - val_loss: 0.3923
Epoch 7/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4004 - val_loss: 0.3842
Epoch 8/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4013 - val_loss: 0.3748
Epoch 9/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - loss: 0.3760 - val_loss: 0.3645
Epoch 10/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3675 - val_loss: 0.3554
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step

Performance:

Accuracy: 0.8616666666666667
Confusion Matrix:
 [[2317   99]
 [ 316  268]]

 training model 

C:\Users\kprat\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5088 - val_loss: 0.4780
Epoch 2/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4959 - val_loss: 0.4469
Epoch 3/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4754 - val_loss: 0.4262
Epoch 4/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4433 - val_loss: 0.4170
Epoch 5/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4404 - val_loss: 0.4128
Epoch 6/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4413 - val_loss: 0.4110
Epoch 7/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4367 - val_loss: 0.4109
Epoch 8/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4299 - val_loss: 0.4093
Epoch 9/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4229 - val_loss: 0.4077
Epoch 10/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4210 - val_loss: 0.4072
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step

Performance:

Accuracy: 0.822
Confusion Matrix:
 [[2318   98]
 [ 436  148]]

 training model with tanh activ

C:\Users\kprat\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6064 - val_loss: 0.4228
Epoch 2/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4361 - val_loss: 0.3944
Epoch 3/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4198 - val_loss: 0.3817
Epoch 4/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3948 - val_loss: 0.3703
Epoch 5/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3844 - val_loss: 0.3578
Epoch 6/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3829 - val_loss: 0.3493
Epoch 7/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3536 - val_loss: 0.3432
Epoch 8/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3595 - val_loss: 0.3383
Epoch 9/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3487 - val_loss: 0.3346
Epoch 10/10
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3436 - val_loss: 0.3332
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step

Performance:

Accuracy: 0.8703333333333333
Confusion Matrix:
 [[2352   64]
 [ 325  259]]
